import Head from 'next/head';
import { useCallback, useState } from 'react';
import { useMux } from '../hooks/useMux';
import { v4 as uuid } from 'uuid';
import { useFileSelect } from '../hooks/useSelectFile';

function Home() {
  const [id, setId] = useState(uuid());
  const { handleUpload, progressPercent } = useMux({ id: id });

  const onSelect = useCallback((acceptedFiles: File[]) => {
    handleUpload(acceptedFiles);
  }, []);

  const { selectFile } = useFileSelect({ onSelect: onSelect });

  return (
    <div>
      <Head>
        <title>Supercut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <button onClick={selectFile}>Upload Video</button>
      {progressPercent}%
    </div>
  );
}

export default Home;
