import Head from 'next/head';
import { SuperStoreProps, useSuperStore } from '../store/useStore';

export default function Home() {
  const setValue = useSuperStore((state: SuperStoreProps) => state.setValue);
  const value = useSuperStore((state: SuperStoreProps) => state.value ?? '');

  return (
    <div>
      <Head>
        <title>Supercut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <input
        placeholder="test value"
        value={value}
        onChange={(e) => setValue({ value: e?.target?.value })}
      />
      value:
      {value}
    </div>
  );
}
